# Generated by Django 3.2.18 on 2023-02-28 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Deny', 'Deny'), ('Excalated', 'Excalated')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('publish', models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('tickets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
