# Generated by Django 3.2.18 on 2023-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish',
            field=models.BooleanField(choices=[('False', False), ('True', True)], default=False),
        ),
    ]
